services:
  postgres:
    container_name: postgres-database
    image: postgres:latest
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - database:/data/postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_HOST=${DB_HOST}

  redis:
    container_name: redis-cache
    restart: always
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes: 
      - redis:/data
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    depends_on:
      - redis
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    - REDIS_USERNAME=${REDIS_USERNAME}
    ports:
    - "8081:8081"

volumes:
  database:
  redis: